/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package common.avro.reviews.entities;
@org.apache.avro.specific.AvroGenerated
public enum ReviewStatus implements org.apache.avro.generic.GenericEnumSymbol<ReviewStatus> {
  PROCESSING, APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ReviewStatus\",\"namespace\":\"common.avro.reviews.entities\",\"symbols\":[\"PROCESSING\",\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
