/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package common.avro.reviews.entities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Review extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2792801083669285768L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Review\",\"namespace\":\"common.avro.reviews.entities\",\"fields\":[{\"name\":\"product_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"created_at\",\"type\":\"long\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"ReviewStatus\",\"symbols\":[\"PROCESSING\",\"APPROVED\",\"REJECTED\"]}},{\"name\":\"review_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rating\",\"type\":\"int\",\"doc\":\"review value, from 1 to 5\"},{\"name\":\"product_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"content\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Review text if provided\",\"default\":null},{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"username\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"user_email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Review> ENCODER =
      new BinaryMessageEncoder<Review>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Review> DECODER =
      new BinaryMessageDecoder<Review>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Review> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Review> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Review> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Review>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Review to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Review from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Review instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Review fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String product_id;
  @Deprecated public long created_at;
  @Deprecated public common.avro.reviews.entities.ReviewStatus status;
  @Deprecated public java.lang.String review_id;
  /** review value, from 1 to 5 */
  @Deprecated public int rating;
  @Deprecated public java.lang.String product_name;
  /** Review text if provided */
  @Deprecated public java.lang.String content;
  @Deprecated public java.lang.String user_id;
  @Deprecated public java.lang.String username;
  @Deprecated public java.lang.String user_email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Review() {}

  /**
   * All-args constructor.
   * @param product_id The new value for product_id
   * @param created_at The new value for created_at
   * @param status The new value for status
   * @param review_id The new value for review_id
   * @param rating review value, from 1 to 5
   * @param product_name The new value for product_name
   * @param content Review text if provided
   * @param user_id The new value for user_id
   * @param username The new value for username
   * @param user_email The new value for user_email
   */
  public Review(java.lang.String product_id, java.lang.Long created_at, common.avro.reviews.entities.ReviewStatus status, java.lang.String review_id, java.lang.Integer rating, java.lang.String product_name, java.lang.String content, java.lang.String user_id, java.lang.String username, java.lang.String user_email) {
    this.product_id = product_id;
    this.created_at = created_at;
    this.status = status;
    this.review_id = review_id;
    this.rating = rating;
    this.product_name = product_name;
    this.content = content;
    this.user_id = user_id;
    this.username = username;
    this.user_email = user_email;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_id;
    case 1: return created_at;
    case 2: return status;
    case 3: return review_id;
    case 4: return rating;
    case 5: return product_name;
    case 6: return content;
    case 7: return user_id;
    case 8: return username;
    case 9: return user_email;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_id = (java.lang.String)value$; break;
    case 1: created_at = (java.lang.Long)value$; break;
    case 2: status = (common.avro.reviews.entities.ReviewStatus)value$; break;
    case 3: review_id = (java.lang.String)value$; break;
    case 4: rating = (java.lang.Integer)value$; break;
    case 5: product_name = (java.lang.String)value$; break;
    case 6: content = (java.lang.String)value$; break;
    case 7: user_id = (java.lang.String)value$; break;
    case 8: username = (java.lang.String)value$; break;
    case 9: user_email = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'product_id' field.
   * @return The value of the 'product_id' field.
   */
  public java.lang.String getProductId() {
    return product_id;
  }


  /**
   * Sets the value of the 'product_id' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.product_id = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public common.avro.reviews.entities.ReviewStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(common.avro.reviews.entities.ReviewStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'review_id' field.
   * @return The value of the 'review_id' field.
   */
  public java.lang.String getReviewId() {
    return review_id;
  }


  /**
   * Sets the value of the 'review_id' field.
   * @param value the value to set.
   */
  public void setReviewId(java.lang.String value) {
    this.review_id = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return review value, from 1 to 5
   */
  public int getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * review value, from 1 to 5
   * @param value the value to set.
   */
  public void setRating(int value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'product_name' field.
   * @return The value of the 'product_name' field.
   */
  public java.lang.String getProductName() {
    return product_name;
  }


  /**
   * Sets the value of the 'product_name' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return Review text if provided
   */
  public java.lang.String getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * Review text if provided
   * @param value the value to set.
   */
  public void setContent(java.lang.String value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.String getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.String getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.String value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'user_email' field.
   * @return The value of the 'user_email' field.
   */
  public java.lang.String getUserEmail() {
    return user_email;
  }


  /**
   * Sets the value of the 'user_email' field.
   * @param value the value to set.
   */
  public void setUserEmail(java.lang.String value) {
    this.user_email = value;
  }

  /**
   * Creates a new Review RecordBuilder.
   * @return A new Review RecordBuilder
   */
  public static common.avro.reviews.entities.Review.Builder newBuilder() {
    return new common.avro.reviews.entities.Review.Builder();
  }

  /**
   * Creates a new Review RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Review RecordBuilder
   */
  public static common.avro.reviews.entities.Review.Builder newBuilder(common.avro.reviews.entities.Review.Builder other) {
    if (other == null) {
      return new common.avro.reviews.entities.Review.Builder();
    } else {
      return new common.avro.reviews.entities.Review.Builder(other);
    }
  }

  /**
   * Creates a new Review RecordBuilder by copying an existing Review instance.
   * @param other The existing instance to copy.
   * @return A new Review RecordBuilder
   */
  public static common.avro.reviews.entities.Review.Builder newBuilder(common.avro.reviews.entities.Review other) {
    if (other == null) {
      return new common.avro.reviews.entities.Review.Builder();
    } else {
      return new common.avro.reviews.entities.Review.Builder(other);
    }
  }

  /**
   * RecordBuilder for Review instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Review>
    implements org.apache.avro.data.RecordBuilder<Review> {

    private java.lang.String product_id;
    private long created_at;
    private common.avro.reviews.entities.ReviewStatus status;
    private java.lang.String review_id;
    /** review value, from 1 to 5 */
    private int rating;
    private java.lang.String product_name;
    /** Review text if provided */
    private java.lang.String content;
    private java.lang.String user_id;
    private java.lang.String username;
    private java.lang.String user_email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(common.avro.reviews.entities.Review.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.created_at)) {
        this.created_at = data().deepCopy(fields()[1].schema(), other.created_at);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.review_id)) {
        this.review_id = data().deepCopy(fields()[3].schema(), other.review_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.rating)) {
        this.rating = data().deepCopy(fields()[4].schema(), other.rating);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.product_name)) {
        this.product_name = data().deepCopy(fields()[5].schema(), other.product_name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.content)) {
        this.content = data().deepCopy(fields()[6].schema(), other.content);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.user_id)) {
        this.user_id = data().deepCopy(fields()[7].schema(), other.user_id);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.username)) {
        this.username = data().deepCopy(fields()[8].schema(), other.username);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.user_email)) {
        this.user_email = data().deepCopy(fields()[9].schema(), other.user_email);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing Review instance
     * @param other The existing instance to copy.
     */
    private Builder(common.avro.reviews.entities.Review other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.product_id)) {
        this.product_id = data().deepCopy(fields()[0].schema(), other.product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.created_at)) {
        this.created_at = data().deepCopy(fields()[1].schema(), other.created_at);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.review_id)) {
        this.review_id = data().deepCopy(fields()[3].schema(), other.review_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.rating)) {
        this.rating = data().deepCopy(fields()[4].schema(), other.rating);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.product_name)) {
        this.product_name = data().deepCopy(fields()[5].schema(), other.product_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.content)) {
        this.content = data().deepCopy(fields()[6].schema(), other.content);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.user_id)) {
        this.user_id = data().deepCopy(fields()[7].schema(), other.user_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.username)) {
        this.username = data().deepCopy(fields()[8].schema(), other.username);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.user_email)) {
        this.user_email = data().deepCopy(fields()[9].schema(), other.user_email);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'product_id' field.
      * @return The value.
      */
    public java.lang.String getProductId() {
      return product_id;
    }


    /**
      * Sets the value of the 'product_id' field.
      * @param value The value of 'product_id'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setProductId(java.lang.String value) {
      validate(fields()[0], value);
      this.product_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product_id' field has been set.
      * @return True if the 'product_id' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'product_id' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearProductId() {
      product_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setCreatedAt(long value) {
      validate(fields()[1], value);
      this.created_at = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearCreatedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public common.avro.reviews.entities.ReviewStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setStatus(common.avro.reviews.entities.ReviewStatus value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'review_id' field.
      * @return The value.
      */
    public java.lang.String getReviewId() {
      return review_id;
    }


    /**
      * Sets the value of the 'review_id' field.
      * @param value The value of 'review_id'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setReviewId(java.lang.String value) {
      validate(fields()[3], value);
      this.review_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'review_id' field has been set.
      * @return True if the 'review_id' field has been set, false otherwise.
      */
    public boolean hasReviewId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'review_id' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearReviewId() {
      review_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * review value, from 1 to 5
      * @return The value.
      */
    public int getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * review value, from 1 to 5
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setRating(int value) {
      validate(fields()[4], value);
      this.rating = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * review value, from 1 to 5
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'rating' field.
      * review value, from 1 to 5
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearRating() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_name' field.
      * @return The value.
      */
    public java.lang.String getProductName() {
      return product_name;
    }


    /**
      * Sets the value of the 'product_name' field.
      * @param value The value of 'product_name'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setProductName(java.lang.String value) {
      validate(fields()[5], value);
      this.product_name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'product_name' field has been set.
      * @return True if the 'product_name' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'product_name' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * Review text if provided
      * @return The value.
      */
    public java.lang.String getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * Review text if provided
      * @param value The value of 'content'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setContent(java.lang.String value) {
      validate(fields()[6], value);
      this.content = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * Review text if provided
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'content' field.
      * Review text if provided
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearContent() {
      content = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setUserId(java.lang.String value) {
      validate(fields()[7], value);
      this.user_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.String getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setUsername(java.lang.String value) {
      validate(fields()[8], value);
      this.username = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearUsername() {
      username = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_email' field.
      * @return The value.
      */
    public java.lang.String getUserEmail() {
      return user_email;
    }


    /**
      * Sets the value of the 'user_email' field.
      * @param value The value of 'user_email'.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder setUserEmail(java.lang.String value) {
      validate(fields()[9], value);
      this.user_email = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'user_email' field has been set.
      * @return True if the 'user_email' field has been set, false otherwise.
      */
    public boolean hasUserEmail() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'user_email' field.
      * @return This builder.
      */
    public common.avro.reviews.entities.Review.Builder clearUserEmail() {
      user_email = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Review build() {
      try {
        Review record = new Review();
        record.product_id = fieldSetFlags()[0] ? this.product_id : (java.lang.String) defaultValue(fields()[0]);
        record.created_at = fieldSetFlags()[1] ? this.created_at : (java.lang.Long) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (common.avro.reviews.entities.ReviewStatus) defaultValue(fields()[2]);
        record.review_id = fieldSetFlags()[3] ? this.review_id : (java.lang.String) defaultValue(fields()[3]);
        record.rating = fieldSetFlags()[4] ? this.rating : (java.lang.Integer) defaultValue(fields()[4]);
        record.product_name = fieldSetFlags()[5] ? this.product_name : (java.lang.String) defaultValue(fields()[5]);
        record.content = fieldSetFlags()[6] ? this.content : (java.lang.String) defaultValue(fields()[6]);
        record.user_id = fieldSetFlags()[7] ? this.user_id : (java.lang.String) defaultValue(fields()[7]);
        record.username = fieldSetFlags()[8] ? this.username : (java.lang.String) defaultValue(fields()[8]);
        record.user_email = fieldSetFlags()[9] ? this.user_email : (java.lang.String) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Review>
    WRITER$ = (org.apache.avro.io.DatumWriter<Review>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Review>
    READER$ = (org.apache.avro.io.DatumReader<Review>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.product_id);

    out.writeLong(this.created_at);

    out.writeEnum(this.status.ordinal());

    out.writeString(this.review_id);

    out.writeInt(this.rating);

    out.writeString(this.product_name);

    if (this.content == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.content);
    }

    out.writeString(this.user_id);

    out.writeString(this.username);

    out.writeString(this.user_email);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.product_id = in.readString();

      this.created_at = in.readLong();

      this.status = common.avro.reviews.entities.ReviewStatus.values()[in.readEnum()];

      this.review_id = in.readString();

      this.rating = in.readInt();

      this.product_name = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.content = null;
      } else {
        this.content = in.readString();
      }

      this.user_id = in.readString();

      this.username = in.readString();

      this.user_email = in.readString();

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.product_id = in.readString();
          break;

        case 1:
          this.created_at = in.readLong();
          break;

        case 2:
          this.status = common.avro.reviews.entities.ReviewStatus.values()[in.readEnum()];
          break;

        case 3:
          this.review_id = in.readString();
          break;

        case 4:
          this.rating = in.readInt();
          break;

        case 5:
          this.product_name = in.readString();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.content = null;
          } else {
            this.content = in.readString();
          }
          break;

        case 7:
          this.user_id = in.readString();
          break;

        case 8:
          this.username = in.readString();
          break;

        case 9:
          this.user_email = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










